// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// The FirebaseOptions object for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // Testweise eingefügt
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The FirebaseOptions object for the web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzkdim6sciIS7kpsuoLBffN8K_Ia4ASxk',
    appId: '1:811713122921:web:fc2f53c4d1d07c012f88f8',
    messagingSenderId: '811713122921',
    projectId: 'zeiterfassung-b92c5',
    authDomain: 'zeiterfassung-b92c5.firebaseapp.com',
    storageBucket: 'zeiterfassung-b92c5.appspot.com',
    measurementId: 'G-Z3J12KLLFD',
  );

  /// The FirebaseOptions object for the android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0V2l5bii3wo0E85NJ72jiDkFvbwMXx2Q',
    appId: '1:811713122921:android:4cb41fec17fb282d2f88f8',
    messagingSenderId: '811713122921',
    projectId: 'zeiterfassung-b92c5',
    storageBucket: 'zeiterfassung-b92c5.appspot.com',
  );

  /// The FirebaseOptions object for the ios platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3AqIAOqq4UJ03ruHC9EpFWOtJ6vAlV0',
    appId: '1:811713122921:ios:e6e00140083ade952f88f8',
    messagingSenderId: '811713122921',
    projectId: 'zeiterfassung-b92c5',
    storageBucket: 'zeiterfassung-b92c5.appspot.com',
    iosClientId: '811713122921-55f2vlhm3qqfhimo8m70pun6hvhc6k32.apps.googleusercontent.com',
    iosBundleId: 'de.cdemy.zeiterfassung',
  );

  /// The FirebaseOptions object for the windows platform.
  static const FirebaseOptions windows = web;
}
